# fly.toml app configuration file generated for shopping-manager-app on 2025-06-10T14:45:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shopping-manager-app'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
