"""empty message

Revision ID: 482de73dcf53
Revises: 8684d2b39ede
Create Date: 2025-06-08 23:56:42.263395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482de73dcf53'
down_revision = '8684d2b39ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglists', schema=None) as batch_op:
        batch_op.drop_column('is_shared')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
