"""empty message

Revision ID: c27f575876df
Revises: 8b54da8b8c5d
Create Date: 2025-06-05 20:30:00.213259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27f575876df'
down_revision = '8b54da8b8c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=True))
        batch_op.alter_column('household_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglists', schema=None) as batch_op:
        batch_op.alter_column('household_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_shared')

    # ### end Alembic commands ###
